### ISSUE TITLE
Doesn't Correctly Identify Bibs on Sample Images

### ISSUE THREAD

**Issue by bodagetta** [KateRita/bib-tagger#1]
I cloned the repo and ran the code, but it is not correctly identifying the bibs. Here is the output

```

Michaels-iMac:bib-tagger michael$ python main.py 
Searching for image folders in /Users/michael/Documents/Developer/Python/bib-tagger/photos folder
Collecting images from directory Frosty5k
Extracting bibs.
=======================================
Processing Image:  ('Frosty5k', '1.jpg')
Found 1 bodies!
0.856932
/Users/michael/Documents/Developer/Python/bib-tagger/bibtagger/swt.py:79: RuntimeWarning: invalid value encountered in true_divide
  grad_x_g = step_x_g / mag_g
/Users/michael/Documents/Developer/Python/bib-tagger/bibtagger/swt.py:80: RuntimeWarning: invalid value encountered in true_divide
  grad_y_g = step_y_g / mag_g
1.062268
2.616008
4.43
Result: 1 faces, 1 bibs, 0 SWT, 1 bib numbers: (['443'])
=======================================
Processing Image:  ('Frosty5k', '2.jpg')
Found 2 bodies!
4.686152
4.926471
6.687606
53 .
8.346033
8.672481
11.097825
1 25
Result: 2 faces, 1 bibs, 0 SWT, 2 bib numbers: (['53', '125'])
=======================================
Processing Image:  ('Frosty5k', '3.jpg')
Found 1 bodies!
13.088198

14.971595

17.342941
732
Result: 1 faces, 1 bibs, 0 SWT, 1 bib numbers: (['732'])
=======================================
Processing Image:  ('Frosty5k', '4.jpg')
Found 3 bodies!
19.198021

19.621269

22.012276
177
23.756217

25.285232

27.524981
131
28.83732

29.817338

33.595866
-375
Result: 3 faces, 3 bibs, 0 SWT, 3 bib numbers: (['177', '131', '375'])
=======================================
Processing Image:  ('Frosty5k', '5.jpg')
Found 3 bodies!
37.081567
37.784887

39.431238
1211
40.283858
3
42.352267
1 4
Result: 3 faces, 1 bibs, 0 SWT, 3 bib numbers: (['1211', '3', '14'])
=======================================
Processing Image:  ('Frosty5k', '6.jpg')
Found 4 bodies!
46.196382

47.380527

51.95717

53.607039

54.132104

56.781109
.5
59.234034

61.504055
18.9
64.773113
1 1
Result: 4 faces, 0 bibs, 0 SWT, 3 bib numbers: (['5', '189', '11'])
=======================================
Processing Image:  ('Frosty5k', 'bib.jpg')
Found 1 bodies!
68.276262
2
Result: 1 faces, 0 bibs, 0 SWT, 1 bib numbers: (['2'])
Collecting images from directory GloryDays
Extracting bibs.
=======================================
Processing Image:  ('GloryDays', '1.jpg')
Found 2 bodies!
69.632925
69.768516
70.736912
1
71.623225
3553
Result: 2 faces, 1 bibs, 0 SWT, 2 bib numbers: (['1', '3553'])
=======================================
Processing Image:  ('GloryDays', '2.jpg')
Found 1 bodies!
73.573601
35 31
Result: 1 faces, 0 bibs, 0 SWT, 1 bib numbers: (['3531'])
=======================================
Processing Image:  ('GloryDays', '3.jpg')
Found 1 bodies!
76.312287
3731
Result: 1 faces, 1 bibs, 0 SWT, 1 bib numbers: (['3731'])
=======================================
Processing Image:  ('GloryDays', '4.jpg')
Found 1 bodies!
77.545362
3 9
Result: 1 faces, 1 bibs, 0 SWT, 1 bib numbers: (['39'])
=======================================
Processing Image:  ('GloryDays', 'bib-sample.jpg')
Found 0 bodies!
Result: 0 faces, 0 bibs, 0 SWT, 0 bib numbers: ([])
=======================================
FINAL STATS
Faces: 20
Bibs: 10
SWT: 0
Bib Numbers: 19
('Bib Index: ',
 {'1': [('GloryDays',
         '1.jpg')],
  '11': [('Frosty5k',
          '6.jpg')],
  '1211': [('Frosty5k',
            '5.jpg')],
  '125': [('Frosty5k',
           '2.jpg')],
  '131': [('Frosty5k',
           '4.jpg')],
  '14': [('Frosty5k',
          '5.jpg')],
  '177': [('Frosty5k',
           '4.jpg')],
  '189': [('Frosty5k',
           '6.jpg')],
  '2': [('Frosty5k',
         'bib.jpg')],
  '3': [('Frosty5k',
         '5.jpg')],
  '3531': [('GloryDays',
            '2.jpg')],
  '3553': [('GloryDays',
            '1.jpg')],
  '3731': [('GloryDays',
            '3.jpg')],
  '375': [('Frosty5k',
           '4.jpg')],
  '39': [('GloryDays',
          '4.jpg')],
  '443': [('Frosty5k',
           '1.jpg')],
  '5': [('Frosty5k',
         '6.jpg')],
  '53': [('Frosty5k',
          '2.jpg')],
  '732': [('Frosty5k',
           '3.jpg')]})
```

**Comment by dennypenta** [comment]
Good day!
I got not the same result, but too awful.
I try to research this project and code something reasonable.
If anybody wanna work with it, let me know pls.

**Comment by robertoarg78** [comment]
just starting and want to help.
first I had to change some functions because I'm using python 3
got the same error "invalid value encountered in true_divide" but I found that is normal, because of some empty areas with no derivative. there's a way to avoid the error message.

**Comment by Jebina** [comment]
I am not not able to run the main.py itself....

Searching for image folders in /var/www/html/multiple_files/bib-tagger-master/photos folder
Collecting images from directory GloryDays
Extracting bibs.
=======================================
Processing Image:  ('GloryDays', '1.jpg')
Found 1 bodies!
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    results.append(bt.findBibs(image,os.path.join(outfolder,img_namelist[idx][0],img_namelist[idx][1])))
  File "/var/www/html/multiple_files/bib-tagger-master/bibtagger/bibtagger.py", line 34, in findBibs
    bibs = [ Bib(image, bodybox) for bodybox in bodyboxes ]
  File "/var/www/html/multiple_files/bib-tagger-master/bibtagger/bib.py", line 10, in __init__
    self.corners = bf.find_bib(self.body_image())
  File "/var/www/html/multiple_files/bib-tagger-master/bibtagger/find_bibs.py", line 23, in find_bib
    threshold_contours,hierarchy = find_contours(binary)
ValueError: too many values to unpack


How did you run the program @bodagetta ???

**Comment by NickShargan** [comment]
@Jebina , probably it is a late response. But if the issue is still actual take a look to issue #5
