### ISSUE TITLE
ValueError: too many values to unpack 

### ISSUE THREAD

**Issue by c769214** [KateRita/bib-tagger#5]
`I just installed the program and got the following error: `

usera@desktop-VBox:~/bib-tagger$ python main.py
Searching for image folders in /home/usera/bib-tagger/photos folder
Collecting images from directory Frosty5k
Extracting bibs.
 ===1====================================
Processing Image:  ('Frosty5k', '1.jpg')
Found 1 bodies!
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    results.append(bt.findBibs(image,os.path.join(outfolder,img_namelist[idx][0],img_namelist[idx][1])))
  File "/home/usera/bib-tagger/bibtagger/bibtagger.py", line 34, in findBibs
    bibs = [ Bib(image, bodybox) for bodybox in bodyboxes ]
  File "/home/usera/bib-tagger/bibtagger/bib.py", line 10, in __init__
    self.corners = bf.find_bib(self.body_image())
  File "/home/usera/bib-tagger/bibtagger/find_bibs.py", line 23, in find_bib
    threshold_contours,hierarchy = find_contours(binary)
ValueError: too many values to unpack

==================

Anything wrong I did ? 

Thanks a  lot

**Comment by NickShargan** [comment]
It is caused by a newer version of OpenCV. It returns 3 objects. To fix this error change:
`threshold_contours,hierarchy = find_contours(binary)`
to 
`_, threshold_contours, hierarchy = find_contours(binary)`
